

services:
  db:
    image: postgres:17
    env_file: 
      - ./Backend/.env
    networks:
      - backend-network
    expose:
      - 5432
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    image: leonidlivshitz/course-project-consortium-backend
    env_file: 
      - './Backend/.env'
    ports:
      - "5000:80"
    depends_on: 
      - db
    restart: always
    networks:
      - backend-network


  frontend:
    image: leonidlivshitz/course-project-consortium-frontend
    restart: always
    depends_on:
      - web
    ports:
      - 3000:80
    networks:
      - backend-network


volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge

