

services:
  db:
    image: postgres:17
    env_file: 
      - ./Backend/.env
    

    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:

    image: leonidlivshitz/course-project-consortium-backend
    build: ./Backend
    env_file: 
      - './Backend/.env'
    ports:
      - "5000:80"
    depends_on: 
      - db
        #condition: service_healthy
    networks:
      - backend-network

  frontend:
    env_file: 
      - './my-app/.env'
    image: leonidlivshitz/course-project-consortium-frontend
    build: ./my-app
    depends_on:
      - web
    ports:
      - 3000:80
    networks:
      - backend-network

  

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge

