"""Reinit with safe translations

Revision ID: 125718e7d38a
Revises: 
Create Date: 2025-02-26 14:34:55.110119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125718e7d38a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=False))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=False))
        batch_op.alter_column('publication_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('materials',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=False))
        batch_op.alter_column('publication_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('materials',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('annotation_en', sa.Text(), nullable=False))
        batch_op.alter_column('publication_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('publication_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('annotation_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('materials',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('materials',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('publication_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
