"""added eng for authors and magazines 1 

Revision ID: 26a6d678e554
Revises: 
Create Date: 2025-03-11 16:01:05.218734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a6d678e554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('content_en')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('content_en')

    # ### end Alembic commands ###
