"""Agil

Revision ID: 9873096b9f66
Revises: 
Create Date: 2025-03-24 19:50:49.344635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9873096b9f66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.drop_constraint('magazine_name_en_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.create_unique_constraint('magazine_name_en_key', ['name_en'])

    # ### end Alembic commands ###
