"""New migration location_en

Revision ID: 9897eef6a73e
Revises: 
Create Date: 2025-04-15 13:00:01.630990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9897eef6a73e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_email_message', ['email', 'message'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_en', sa.String(length=100), nullable=True))

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location_en')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('uq_email_message', type_='unique')

    # ### end Alembic commands ###
