"""changed nullable to True _en 5 

Revision ID: 9a0890e1de23
Revises: 
Create Date: 2025-03-04 15:01:03.653689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0890e1de23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('annotation_en',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('annotation_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
