"""added eng for authors and magazines_1 

Revision ID: a1a3b565074e
Revises: 
Create Date: 2025-03-11 14:34:20.184971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a3b565074e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name_en', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name_en', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('middle_name_en', sa.String(length=50), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['name_en'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('annotation_en',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.alter_column('annotation_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name_en')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('middle_name_en')
        batch_op.drop_column('last_name_en')
        batch_op.drop_column('first_name_en')

    # ### end Alembic commands ###
