"""added eng for authors and magazines 

Revision ID: f1f314a48ee8
Revises: 
Create Date: 2025-03-11 14:11:27.729271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f314a48ee8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name_en', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name_en', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('middle_name_en', sa.String(length=50), nullable=True))

    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['name_en'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magazine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name_en')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('middle_name_en')
        batch_op.drop_column('last_name_en')
        batch_op.drop_column('first_name_en')

    # ### end Alembic commands ###
