# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Pytest
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        cd Backend
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pwd
        cd Backend
        cp .env.example .env
        ls -a
        pytest -s --cov --cov-report html --cov-fail-under 100